### ISSUE TITLE
兄弟，我启动成功，启动类运行成功了，用户信息也放进去了，打印了步数显示更改成功，但是没有更改。

### ISSUE THREAD

**Issue by 2416941966** [niushuai233/mi-sport-change#4]
兄弟，我启动成功，启动类运行成功了，用户信息也放进去了，打印了步数显示更改成功，但是没有更改。

18:22:07.994 [main] INFO cc.niushuai.misportchange.stepchange.biz.MiStepBiz - 5、修改步数
18:22:08.344 [main] INFO cc.niushuai.misportchange.stepchange.biz.MiStepBiz - doChange: {"code":1,"message":"success"}
18:22:08.344 [main] INFO cc.niushuai.misportchange.stepchange.biz.MiStepBiz - 用户: xxxxxxxxxxx, 修改步数为: 23000, 成功

**Comment by 2416941966** [comment]
小米运动啥的也配置了的。

**Comment by niushuai233** [comment]
这个不能保证每次都是正常运行的，时不时的可能需要更新

**Comment by niushuai233** [comment]
这种方式可靠性需要更新，最近是通过xp框架修改倍率  主要是给我女朋友用的 哈哈
