### ISSUE TITLE
接口调用成功，但是实际步数没有修改成功

### ISSUE THREAD

**Issue by vokenfan** [niushuai233/mi-sport-change#6]
这是咋回事，你知道吗，兄弟

**Comment by niushuai233** [comment]
> 这是咋回事，你知道吗，兄弟



> 这是咋回事，你知道吗，兄弟

我昨天还在用呀，这个其实是主要为了蚂蚁森林搞的玩意

**Comment by niushuai233** [comment]
> 这是咋回事，你知道吗，兄弟

用代码，不用release就好
